# Generated by Django 3.1.1 on 2020-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='c_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
