# Generated by Django 3.1.1 on 2020-09-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chefcreate',
            table='chef_create',
        ),
    ]
