# Generated by Django 3.1.1 on 2020-09-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200926_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefcreate',
            name='c_id',
        ),
    ]
