# Generated by Django 3.1.1 on 2020-09-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200925_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chef',
        ),
    ]
