# Generated by Django 3.1.1 on 2020-09-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_chefcreate_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefcreate',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='chefcreate',
            name='password',
        ),
    ]
