# Generated by Django 3.1.1 on 2020-09-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chef_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='chef',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
