# Generated by Django 3.1.1 on 2020-09-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200927_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefcreate',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
