# Generated by Django 3.1.1 on 2020-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200926_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefuser',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
